# Generated by Django 6.0.1 on 2026-01-14 21:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_authorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorapplication',
            name='content',
        ),
        migrations.AlterField(
            model_name='authorapplication',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
